### ISSUE TITLE
Docker build fails on Step 6

### ISSUE THREAD

**Issue by mjgpy3** [SuaveIO/suave#507]
Hello, I'm not entirely sure why but building a docker image from the included Dockerfile is failing.

I'm running

```
docker build -t test . 
```

The output I'm seeing is

> Step 6 : RUN bundle exec rake dotnetcli:restore dotnetcli:build compile
>  ---> Running in c57cef8cd62c
> mkdir -p tools/coreclr
> .NET Core SDK 1.0.0-preview2-003121 not found. Downloading and installing in ./tools/coreclr
> curl -o tools/dotnet-dev-ubuntu.14.04-x64.1.0.0-preview2-003121.tar.gz -L https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-003121/dotnet-dev-ubuntu.14.04-x64.1.0.0-preview2-003121.tar.gz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   215  100   215    0     0    481      0 --:--:-- --:--:-- --:--:--   482
> tar xf tools/dotnet-dev-ubuntu.14.04-x64.1.0.0-preview2-003121.tar.gz --directory tools/coreclr
> tar: This does not look like a tar archive
> 
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> rake aborted!
> Albacore::CommandFailedError: Command failed with status (2):
>   tar xf tools/dotnet-dev-ubuntu.14.04-x64.1.0.0-preview2-003121.tar.gz --directory tools/coreclr
> 
> /var/lib/gems/1.9.1/gems/albacore-2.6.1/lib/albacore/cross_platform_cmd.rb:263:in `raise_failure'
> /var/lib/gems/1.9.1/gems/albacore-2.6.1/lib/albacore/cross_platform_cmd.rb:242:in`block in handler_with_message'
> /var/lib/gems/1.9.1/gems/albacore-2.6.1/lib/albacore/cross_platform_cmd.rb:111:in `call'
> /var/lib/gems/1.9.1/gems/albacore-2.6.1/lib/albacore/cross_platform_cmd.rb:111:in`block in system'
> /var/lib/gems/1.9.1/gems/albacore-2.6.1/lib/albacore/cross_platform_cmd.rb:247:in `handle_not_found'
> /var/lib/gems/1.9.1/gems/albacore-2.6.1/lib/albacore/cross_platform_cmd.rb:87:in`system'
> /suave-build/Rakefile:137:in `block (2 levels) in <top (required)>'
> Tasks: TOP => dotnetcli:restore => dotnetcli:coreclr_binaries
> (See full trace by running task with --trace)
> The command '/bin/sh -c bundle exec rake dotnetcli:restore dotnetcli:build compile' returned a non-zero code: 1

**Comment by haf** [comment]
It's because MSFT has moved the cheese again, /cc @enricosada 

<img width="1228" alt="screen shot 2016-09-21 at 09 53 04" src="https://cloud.githubusercontent.com/assets/193115/18702267/3a71a20e-7fe1-11e6-95bb-1db73d5fe545.png">

**Comment by haf** [comment]
Should be fixed by https://github.com/SuaveIO/suave/commit/b1bde85f33581f3f601158a9ef045be36cc6801a

**Comment by mjgpy3** [comment]
Unfortunately, it's still not working. Here's my output

> Step 6 : RUN bundle exec rake dotnetcli:restore dotnetcli:build compile
 ---> Running in de1e76890f57
mkdir -p tools/coreclr
.NET Core SDK 1.0.0-preview2-003131 not found. Downloading and installing in ./tools/coreclr
curl -o tools/dotnet-dev-ubuntu.14.04-x64.1.0.0-preview2-003131.tar.gz -L https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-003131/dotnet-dev-ubuntu.14.04-x64.1.0.0-preview2-003131.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   215  100   215    0     0    470      0 --:--:-- --:--:-- --:--:--   469
tar xf tools/dotnet-dev-ubuntu.14.04-x64.1.0.0-preview2-003131.tar.gz --directory tools/coreclr
tar: This does not look like a tar archive

> gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
rake aborted!
Albacore::CommandFailedError: Command failed with status (2):
  tar xf tools/dotnet-dev-ubuntu.14.04-x64.1.0.0-preview2-003131.tar.gz --directory tools/coreclr

> /var/lib/gems/1.9.1/gems/albacore-2.6.1/lib/albacore/cross_platform_cmd.rb:263:in `raise_failure'
/var/lib/gems/1.9.1/gems/albacore-2.6.1/lib/albacore/cross_platform_cmd.rb:242:in `block in handler_with_message'
/var/lib/gems/1.9.1/gems/albacore-2.6.1/lib/albacore/cross_platform_cmd.rb:111:in `call'
/var/lib/gems/1.9.1/gems/albacore-2.6.1/lib/albacore/cross_platform_cmd.rb:111:in `block in system'
/var/lib/gems/1.9.1/gems/albacore-2.6.1/lib/albacore/cross_platform_cmd.rb:247:in `handle_not_found'
/var/lib/gems/1.9.1/gems/albacore-2.6.1/lib/albacore/cross_platform_cmd.rb:87:in `system'
/suave-build/Rakefile:137:in `block (2 levels) in <top (required)>'
Tasks: TOP => dotnetcli:restore => dotnetcli:coreclr_binaries
(See full trace by running task with --trace)
The command '/bin/sh -c bundle exec rake dotnetcli:restore dotnetcli:build compile' returned a non-zero code: 1
